spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${APP_CONNECTION_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    enable:
      hikari: true

server:
  tomcat:
    threads:
      max: ${APP_THREAD_POOL_SIZE}
    mbeanregistry:
      enabled: true # 이 설정이 있어야 Tomcat 상세 메트릭이 수집됩니다.