spring:
  data:
    redis:
      host: toxiproxy
      port: 8666
#      sentinel:
#        master: ${REDIS_SENTINEL_MASTER:mymaster}
#        nodes: ${REDIS_SENTINEL_NODES:localhost:26379,localhost:26380,localhost:26381}
      timeout: ${REDIS_TIMEOUT:150ms}
      connect-timeout: ${REDIS_CONNECTION_TIMEOUT:100ms}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      participationCache:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5           # prod: 10
        minimum-number-of-calls: 3       # prod: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 80
        wait-duration-in-open-state: 10s # prod: 30s
        permitted-number-of-calls-in-half-open-state: 2  # prod: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException
          - org.springframework.data.redis.RedisSystemException
          - org.springframework.dao.QueryTimeoutException
      ignore-exceptions:
        - io.github.resilience4j.bulkhead.BulkheadFullException

  retry:
    retry-aspect-order: 2
    instances:
      participationCache:
        max-attempts: 3
        wait-duration: 50ms              # prod: 100ms
        retry-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException
          - org.springframework.data.redis.RedisSystemException
          - org.springframework.dao.QueryTimeoutException

  bulkhead:
    instances:
      sendMessage:
        max-concurrent-calls: 1         # prod: 70
        max-wait-duration: 0ms

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,retries,bulkheads,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    io.github.resilience4j: DEBUG
    io.github.jaehyeonhan.project: DEBUG
